config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  devise_for :users,  :controllers => { registrations: "registrations"}
  resources :users

  resources :perfils
  resources :barbacoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barbacoa.rb
class Barbacoa < ApplicationRecord
  belongs_to :perfil
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode#, if: :will_save_change_to_address?
end

app/models/perfil.rb
class Perfil < ApplicationRecord
  belongs_to :user
  has_many :barbacoas
  validates :nombre, :apellido, :phone, presence: true, on: :update

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :perfil

  def has_perfil?
    self.perfil != nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/barbacoas_controller.rb
class BarbacoasController < ApplicationController
  def index

  end

  def show
    @barbacoa = Barbacoa.find(params[:id])
    @perfil = Perfil.find(@barbacoa.perfil)
  end

  def new
    # @perfil = Perfil.find(params[:rider_id])
    @barbacoa = Barbacoa.new
  end

  def create
    @barbacoa= Barbacoa.new(barbacoa_params)
    @barbacoa.perfil = current_user.perfil
    @barbacoa.save
    redirect_to root_path
  end

  def edit
    @barbacoa = Barbacoa.find(params[:id])

  end

  def update
    @barbacoa = Barbacoa.find(params[:id])
    @barbacoa.update(barbacoa_params)
    redirect_to barbacoa_path(@barbacoa)
  end

  private

  def barbacoa_params
    params.require(:barbacoa).permit(:titulo,:modelo,:disponible,:descripcion,:address,:precio,:photo)
  end

  def set_perfil
    @perfilr = Perfil.find(params[:rider_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
    @bbqs = Barbacoa.all
    @bbq = Barbacoa.where.not(latitude: nil, longitude: nil)
     @markers = @bbq.map do |l|
      {
        lat: l.latitude,
        lng: l.longitude#,
      }
    end
  end

end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController

  def index
    @perfiles = Perfil.all
  end

  def show
    @user = current_user
    @perfil = Perfil.find(params[:id])
  end

  def edit
    @perfil = Perfil.find(params[:id])
  end

  def update
    @perfil = Perfil.find(params[:id])
    @perfil.update(perfil_params)
    redirect_to root_path
  end


  private

  def perfil_params
    params.require(:perfil).permit(:nombre, :apellido, :phone)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super do |user|
      Perfil.create(user_id: user.id) if user.id
    end
  end

  protected

  def after_sign_up_path_for(resource)
    if resource.perfil
      edit_perfil_path(resource.perfil)
    else
      super(resource)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barbacoas_helper.rb
module BarbacoasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/barbacoas/edit.html.erb
<div class="container">
  <br>
  <h2>Nuevo bbq</h2>
  <br>
  <p>Ingresa los datos de la barbabacoa que deseas agregar</p>
  <%= simple_form_for [@perfil, @barbacoa] do |f| %>
  <%= f.input :titulo %>
  <%= f.input :modelo %>
  <%= f.input :disponible %>
  <%= f.input :descripcion %>
  <%= f.input :address %>
  <p>Precio por dia</p>
  <%= f.input :precio %>
  <br>
  <%= f.submit class: "btn btn-danger" %>
  <% end %>
</div>

app/views/barbacoas/new.html.erb
 <div class="container">
  <br>
  <h2>Nuevo bbq</h2>
  <br>
  <p>Ingresa los datos de la barbabacoa que deseas agregar</p>
  <%= simple_form_for [@perfil, @barbacoa] do |f| %>
  <%= f.input :titulo %>
  <%= f.input :modelo %>
  <%= f.input :disponible %>
  <%= f.input :descripcion %>
  <p>Precio por dia</p>
  <%= f.input :precio %>
  <%= f.input :address %>
   <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <br>
  <%= f.submit class: "btn btn-danger" %>
  <% end %>
</div>

app/views/barbacoas/show.html.erb
<div class="container">
 <div class="top text-center logo space">
  <%= image_tag("logo.png")%>
  <h2>BBQ community</h2>
  <h3>Rent you BBQ's</h3>
  <br>
  <div class="text-center">
   <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo">Options</button>
 </div>
 <hr>
 <div id="demo" class="collapse text-center route space">
  <h3><%= link_to "Home", root_path%></h3>
  <h3><%= link_to "Perfil", perfil_path(current_user.perfil)%></h3>
  <hr>
</div>
</div>
<div class="container text-center">
  <%= cl_image_tag @barbacoa.photo, height: 200, crop: :fill %>

  <h2><%= @barbacoa.titulo.capitalize %> </h2>
  <h4><%= @barbacoa.modelo %></h4>
  <% if @barbacoa.disponible === TRUE %>
  <p style="color: #22ea63 !important;">Disponible</p>
  <% else %>
  <p style="color: #e4180a !important;">No disponible</p>
  <% end %>
  <p><%= @barbacoa.descripcion%></p>
  <h5>Precio por dia</h5>
  <h3><%= @barbacoa.precio%> $</h3>
  <h3>Dirreccion</h3>
  <p><%= @barbacoa.address %></p>
  <%if current_user.perfil.id == @perfil.id%>
  <h3><%= link_to "Edit", edit_barbacoa_path(@barbacoa),  class: "btn btn-danger"%></h3>
  <% else %>
  <h3><%= link_to "Rentar", perfil_path(@barbacoa.perfil),  class: "btn btn-danger" %></h3>
  <%end%>
</div>

</div>

<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbq</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <meta charset="utf-8">
  <style>
  .logo img {
    height: 100px;
  }
  .space {
    padding-bottom: 30px;
  }
  a, u {
    text-decoration: none !important;
    color: black;
  }
</style>
</head>
</head>
<body>

  <%= render 'shared/navbar' %>
  <%= yield %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%#= javascript_include_tag('map.js') %>
  <%#= javascript_include_tag :defaults %>

</body>
</html>

app/views/pages/home.html.erb
<hr>
<div class="container">
  <% if user_signed_in? %>
 <div class="top text-center logo space">
  <%= image_tag("logo.png")%>
  <h2>BBQ community</h2>
    <h3>Rent you BBQ's</h3>
  <br>
  <div class="text-center">
   <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo">Options</button>
  </div>
      <hr>
  <div id="demo" class="collapse text-center route space">
    <h3><%= link_to "Home", root_path%></h3>
    <h3><%= link_to "Perfil", perfil_path(current_user.perfil)%></h3>
    <hr>
  </div>
</div>
  <% @bbqs.each do |bbq|%>
<div class="col-xs-12">
  <%= link_to barbacoa_path(bbq) do %>
  <div class="text-center logo">
    <%= cl_image_tag bbq.photo, height: 200, crop: :fill %>
    <p><%= bbq.titulo %></p>
    <p><%= bbq.modelo %></p>
  <% end %>
   <% if bbq.disponible === TRUE %>
      <p style="color: #22ea63 !important;">Disponible</p>
      <br>
      <% else %>
      <p style="color: #e4180a !important;">No disponible</p>
      <br>
    <% end %>
    </div>
    <% end %>
</div>
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>

</div>
  <% else %>
  <div class="container">
  <div class="jumbotron">
    <h2>BBQ community</h2>
    <h3>Rent you BBQ's</h3>
    <%= link_to "Sing up", new_user_registration_path, class: "btn btn-danger"%>
  </div>

</div>

<% end %>

app/views/perfils/edit.html.erb
   <div class="container">
    <h1>Perfil</h1>
          <%= simple_form_for @perfil do |f| %>
              <%= f.input :nombre %>
              <%= f.input :apellido %>
              <%= f.input :phone %>
              <br>
              <%= f.submit class: "btn btn-danger"%>
          <% end %>
  </div>
</div>

app/views/perfils/show.html.erb
<% if user_signed_in? %>
<div class="container">
   <div class="top text-center logo space">
  <%= image_tag("logo.png")%>
  <h2>BBQ community</h2>
  <h3>Rent you BBQ's</h3>
  <br>
  <div class="text-center">
   <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo">Options</button>
 </div>
 <hr>
 <div id="demo" class="collapse text-center route space">
  <h3><%= link_to "Home", root_path%></h3>
  <h3><%= link_to "Perfil", perfil_path(current_user.perfil)%></h3>
  <hr>
</div>
</div>
  <div class="jumbotron">
    <h2>Rent ur BBQ</h2>
    <hr>
    <%if current_user.perfil.id != @perfil.id%>
      <h2>Contacta</h2>
    <%end%>
    <h4> <%= current_user.perfil.nombre + " " +@perfil.apellido%></h4>
    <h4> <%= current_user.perfil.phone %> </h4>
    <h4><%= current_user.email %> </h4>
   <%if current_user.perfil.id == @perfil.id%>
    <h2><%= link_to "Edit", edit_perfil_path(current_user.perfil), class: "btn btn-danger" %></h2>
    <% end %>
  </div>
</div>
<%if current_user.perfil.id == @perfil.id%>
<h2 class="text-center"><%= link_to "Add bbq",new_barbacoa_path(current_user.perfil), class: "btn btn-danger" %></h2>
<% end %>
<div class="container space">
<% @perfil.barbacoas.reverse.each do |bbq|%>
<div class="col-md-4">
  <%= link_to barbacoa_path(bbq) do %>
  <div class="text-center logo">
    <%= cl_image_tag bbq.photo, height: 200, crop: :fill %>
    <p><%= bbq.titulo %></p>
    <p><%= bbq.modelo %></p>
  <% end %>
   <% if bbq.disponible === TRUE %>
      <p style="color: #22ea63 !important;">Disponible</p>
      <% else %>
      <p style="color: #e4180a !important;">No disponible</p>
    <% end %>
    </div>
</div>
<% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container">
    <% if user_signed_in? %>
    <h2><%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, class: "btn btn-danger", method: :delete %></h2>
    <% else %>
    <!-- Login link (when logged out) -->
    <h2><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-danger" %></h2>
    <% end %>
</div>